
# PARTE 2 DEL RECOMENDADOR DE CARTERAS:

# ESTA PARTE PERMITE REALIZAR EL CRUCE ENTRE LA TABLA DE TENENCIA Y LA BASE DEL MANTENEDOR
# DE EJECUTIVOS POR CUENTA
# CUALQUIER DUDA CONSULTAR AL AUTOR: 
# RODRIGO ESCOBAR LANDAETA | RESCOBARL@FEN.UCHILE.CL | LANDAETA77@GMAIL.COM


library(readr)
library(dplyr)
library(tidyquant)


# CARGA DE ARCHIVO CRM DE TENENCIA

PRECIOS_ACCIONES <- read_csv2("FILES/INTERMEDIO/01_PRECIOS_ACCIONES.CSV")
BASE_CUSTODIA <- read_csv2("FILES/INTERMEDIO/02_BASE_CUSTODIA_PRINCIPAL.CSV")



# CRUCE TABLA SHARES PARA OBTENER EJECUTIVO ASIGNADO


BASE_CUSTODIA<-BASE_CUSTODIA%>%left_join(PRECIOS_ACCIONES, by="ID_EMPRESA")





